### PR TITLE
Add capture group option for `GrammaredSequence.to_regex` fixes #1431

### LINKED ISSUE #1431: Feature Request: Using DNA.find_with_regex and DNA.as_regex together
One thing I wish was possible is using `skbio.DNA.find_with_regex` and `skbio.sequence.GrammaredSequence.to_regex` together. This is most useful when considering DNA patterned with degenerate bases such as the pattern `RGYW`.

[to_regex() documentation](http://scikit-bio.org/docs/0.4.2/generated/skbio.sequence.GrammaredSequence.to_regex.html)
[find_with_regex() documentation](http://scikit-bio.org/docs/0.4.2/generated/skbio.sequence.Sequence.find_with_regex.html)

Example usage:

```python
from skbio import DNA

reference = DNA("GGTA")
motif = DNA("RGYW")

for match in reference.find_with_regex(motif.as_regex()):
     pass # One match result yield here
```

The issue is that `find_with_regex` looks for match groups which `as_regex` does not include. Would this be possible to implement?

### PR DESCRIPTION
**Pull request by clintval**
* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

---

This PR implements #1431. Sorry for the delay.

This is my first time contributing and I would love to continue so please let me know if everything checks out!

### CODE REVIEW

**Comment by clintval** [comment]
Any chance of a review or merge?

**Comment by clintval** [comment]
Hi @RNAer the use case for wrapping the pattern in a capture group:

```python
>>> from skbio import DNA
>>> print(list(DNA("GGTA").find_with_regex(DNA("RGYW").to_regex(capture=False))))
>>> print(list(DNA("GGTA").find_with_regex(DNA("RGYW").to_regex(capture=True))))
[]
[slice(0, 4, None)]
```
I also rebased on `master` and changed the `CHANGELOG.md` for you.

**Comment by clintval** [comment]
Would the argument `as_capture` be more descriptive than just `capture`?

**Comment by RNAer** [comment]
Thanks, @clintval ! Now I get fully understanding of the problem. API-wise, I would argue to modify `find_with_regex` instead. It's not intuitive that users have to capture their seq pattern inside parentheses. `find_with_regex` should work without the parentheses. Are you interested to update your PR for that?

**Comment by clintval** [comment]
@RNAer , I agree, let me try! Thanks!

**Comment by RNAer** [comment]
Thanks!

**Comment by clintval** [comment]
Hi @RNAer just taking a look at this again.

I don't think what you are asking for would be very elegant or efficient as it would require compiling a regex pattern twice. Once with default behavior `to_regex()`, and then a second time to add the capture group parenthesis with `find_with_regex()` as you proposed.


An example how that looks, notice two pattern compilations since `to_regex()` is unchanged:

```python
>>> import re
>>> from skbio import DNA

>>> dna = DNA('RGYW')
>>> regex = dna.to_regex()
>>> regex
re.compile(r'[AG]G[TC][AT]', re.UNICODE)

>>> new_pattern = f'({regex.pattern})'
>>> new_regex = re.compile(new_pattern)
>>> new_regex
re.compile(r'([AG]G[TC][AT])', re.UNICODE)
```

Instead I would prefer the API have the user add arguments to `to_regex()` to modify the resulting compiled regex pattern as initially proposed, so the pattern becomes:

```python
>>> from skbio import DNA

>>> query = DNA('RGYW')

>>> query.to_regex()                        # Current Behavior
re.compile(r'[AG]G[TC][AT]', re.UNICODE)

>>> query.to_regex(within_capture=True)     # Proposed Option
re.compile(r'([AG]G[TC][AT])', re.UNICODE)
```

Only when a capture group is added to the pattern is anything returned by `DNA.find_with_regex()`:

```python
>>> query = DNA('RGYW')
>>> DNA('AGTA').find_with_regex(query.to_regex(within_capture=True))
[slice(0, 4, None)]
```

**Comment by clintval** [comment]
@RNAer any chance for a review or merge? I had added a few more comments to:

https://github.com/biocore/scikit-bio/issues/1431

I would like to see this merged in so I can stop relying on personal `skbio` forks, the feature has been helpful.

**Pull request merged**
