### PR TITLE
Pandas==0.22.0

### PR DESCRIPTION
**Pull request by antgonza**
Please complete the following checklist:

* [X] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [X] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [ ] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by mortonjt** [comment]
Thanks @antgonza !  I think this should fix the issues in #1577 and #1583

@RNAer @wasade could you take a look at this?  Note that this is a temporary fix for now - we'll likely want to upgrade to the newest version of pandas in the future

**Comment by wasade** [comment]
Pinning this to a specific version will likely introduce a lot of dependency challenges for downstream use. Does it _really_ need to be a specific major.minor.micro version?

**Comment by antgonza** [comment]
From my testing, it has to be <= 0.22.0, 0.23.0, 0.23.1 and dev (0.24.0) do not work. Should I make it that?

**Comment by wasade** [comment]
That would allows for quite a bit more flexibility. What about < 0.23.0 so that micro version changes of 0.22.0 are allowed?

**Pull request merged**
