### PR TITLE
Allow subclasses of TreeNode to be used

### PR DESCRIPTION
**Pull request by terrycojones**
I've just started using scikit-bio (thanks!) and ran into something a little inflexible that I think could be improved quite easily.

I'd like to have my own `TreeNode` class so I can store attributes and methods on it. This issue has come up in various other guises, see e.g., #1117, #809, and #465.

If I can't use my own subclass, I need to keep per-node metadata somewhere else, and keep it up to date, etc. E.g., I could make a class, `MyClass`, that keeps a `TreeNode` instance (e.g., called `tree`) plus some other metadata. This is quite inconvenient and un-Pythonic. It means I need to call the extra methods of my class using things like

```python
myClass = MyClass()
for node in myClass.tree.children:
    if myClass.nodeSupport(node) > 0:
        # pass
```

rather than the simpler approach in which I subclass `TreeNode` and add the methods and attributes I want.  The simpler approach also makes testing easier.

Anyway, the usual way to do this is to pass around a class that is used to make new tree nodes, and have it default to the original simple base class (`TreeNode` in this case).

I'm not proposing that this pull request gets merged at the moment, but would like to see what people think of the idea and the simple diff.  If this seems like a good direction, I can add some tests that subclass `TreeNode` and which pass a `tree_node_class` argument to `majority_rule`.

Thanks again for scikit-bio!

### CODE REVIEW

**Comment by wasade** [comment]
:+1:, this used to be handled through a `constructor` `kwarg` in pycogent. It was dropped as, in practice, it wasn't used and led to confusion in the code base. We do need some mechanism that cleanly allows for subclassing support in ancillary methods. 

With the current object, there shouldn't be an issue with decorating on your own attributes, and they'll automatically be represented during copy operations, for instance. But, I also completely agree that the metadata representation does need to be rethought on this object.

**Comment by terrycojones** [comment]
Hi @wasade 

Thanks. I can add attributes myself to `TreeNode` instances, but it's quite cumbersome in some cases. E.g., if I call a `TreeNode` method that alters the tree, I may need to walk the tree myself to see if I need to add/update my attributes on all nodes (some nodes may be new, some nodes may have different numbers of siblings or whatever, etc). Or if I want to change the behavior of any of the existing methods (even something simple, like `__str__`), it'd be a real pain. Adding something like `__eq__`, as several people seem to have wanted to do (perhaps in quite different ways, which can be done trivially via subclasses), is also hard. Of course these things can be done with additional (external) functions, but that's awkward too.

**Comment by wasade** [comment]
Ya, agree it is not ideal. Thanks for opening the issue!

**Comment by jairideout** [comment]
Closing in favor of #1364, which contains the commits in this PR and some updates. Thanks for your contribution @terrycojones!

**Pull request closed without merging**
