### PR TITLE
Replaced cachecontrol with requests

### PR DESCRIPTION
**Pull request by qiyunzhu**
This is the consensus from the discussion in #1858 . Basically, it replaced the CacheControl library which is prone to dependency issues with the widely adopted Requests library (which is also a dependency of the former, as well as of QIIME 2 and scikit-bio). The caching feature is abandoned, but it is probably not necessary since other popular Python libraries also don't cache. @wasade @mortonjt .

Tested and working. The following codes produced the same result.

```python
# use_cachecontrol.py 
import io
import tempfile
import requests
from cachecontrol import CacheControl
from cachecontrol.caches import FileCache

url = 'https://data.qiime2.org/2023.5/tutorials/moving-pictures/sample_metadata.tsv'

sess = CacheControl(requests.Session(), cache=FileCache(tempfile.gettempdir()))
req = sess.get(url)
req.raise_for_status()
res = io.BufferedReader(io.BytesIO(req.content))

with open('metadata.tsv', 'wb') as f:
    f.write(res.read())
```

```python
# use_requests.py 
import io
import requests

url = 'https://data.qiime2.org/2023.5/tutorials/moving-pictures/sample_metadata.tsv'

req = requests.get(url)
req.raise_for_status()
res = io.BufferedReader(io.BytesIO(req.content))

with open('metadata.tsv', 'wb') as f:
    f.write(res.read())
```

The requests version 2.20.0 is somewhere slightly above the lowest version found in conda pkg-main.

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
The code in the PR has been merged into #1859 . The latter should pass all build tests.

**Comment by wasade** [comment]
Doctest failure on with the blast result :/

**Comment by qiyunzhu** [comment]
It should be #1859 worth merging. Thanks!

**Comment by qiyunzhu** [comment]
Merged into #1859 .

**Pull request closed without merging**
