### PR TITLE
Hommola cospeciation test (skbio.stats.evolve)

### PR DESCRIPTION
**Pull request by jairideout**
Includes the commits in #557. I made some minor changes, including:

- a few stylistic/readability changes to the code
- docstring updates for clarity
- subpackage restructuring to match latest scikit-bio codebase
- removed sorting of vectors before Pearson calls (will resolve as part of #810 across the codebase)

@tanaes do you mind taking a look at these changes? @ebolyen and/or @gregcaporaso can you also review?

### CODE REVIEW

**Comment by jairideout** [comment]
@ebolyen this is now ready for review (I believe @tanaes comments are addressed in the commit comments). Multiple developers have reviewed already, so a quick review should be fine.

**Comment by ebolyen** [comment]
Looks excellent. No comments. Thanks @tanaes and @jairideout!

**Comment by jairideout** [comment]
Thanks @ebolyen for reviewing, and thanks @tanaes for all of your work on this new subpackage!

**Comment by tanaes** [comment]
You bet -- it was super fun! Thanks for guiding me through my first GitHub
contribution. Hope to add more to this package soon.

-j

On Fri, Mar 27, 2015 at 8:14 PM, Jai Ram Rideout <notifications@github.com>
wrote:

> Thanks @ebolyen
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ebolyen&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=HH7jG2Tt8197HNR9p8tbXSGeEwcBM0prLzmrvLXVX5Q&m=E8o6LbcQj_0fyW4wMu5q1DYgPMsv7k6FygcDcpDGI7o&s=mtEYUmjzlNDHtVSOXMYCOh-EkngUfT3UrQ3qeK1rsog&e=>
> for reviewing, and thanks @tanaes
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tanaes&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=HH7jG2Tt8197HNR9p8tbXSGeEwcBM0prLzmrvLXVX5Q&m=E8o6LbcQj_0fyW4wMu5q1DYgPMsv7k6FygcDcpDGI7o&s=aF0HZ8Zv4Fxx2xJigag0T9ILlprZjkKNuqzoJ-drnBo&e=>
> for all of your work on this new subpackage!
>
> --
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_biocore_scikit-2Dbio_pull_877-23issuecomment-2D87128529&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=HH7jG2Tt8197HNR9p8tbXSGeEwcBM0prLzmrvLXVX5Q&m=E8o6LbcQj_0fyW4wMu5q1DYgPMsv7k6FygcDcpDGI7o&s=CQk2LL8o90EL594x3KFRVVvEf4nhbMoKe_WkgS1Bl-w&e=>
> .
>



-- 
"If you hold a cat by the tail you learn things you cannot learn any other
way."
                         --Mark Twain

**Pull request merged**
