### PR TITLE
Addresses #1259

### PR DESCRIPTION
**Pull request by mortonjt**
Swapping out the mann-whitney U-test with a t-test.

Note, this only swaps out this statistical test in the broken test cases.

### CODE REVIEW

**Comment by Jorge-C** [comment]
I was about to complain that swapping a robust Mann–Whitney U test with a t-test doesn't seem valid, then I read your note, and it's just a small test case edit :)

Before changing this I feel we should really understand what changed between versions, as Jai mentioned in #1259. Were the values wrong previously?

**Comment by mortonjt** [comment]
I'm not exactly sure what is going on.  Looks like these changes were made in this [commit](https://github.com/scipy/scipy/commit/424128b563f291c71f1a123071f37e1cb22312bd)

**Comment by Jorge-C** [comment]
Thanks! I'll have a look too.

**Comment by jairideout** [comment]
Thanks @mortonjt and @Jorge-C for looking into this. I agree it would be nice to figure out why we're seeing differences between versions. However, `mannwhitneyu` has had (and still has) a slew of bugs related to tie correction and/or p-values (take a look at issues/PRs related to this function [here](https://github.com/scipy/scipy/search?q=mann&type=Issues&utf8=%E2%9C%93)). IMO `mannwhitneyu`'s buggy behavior is outside the scope of scikit-bio because we aren't advertising usage of `mannwhitneyu` in the docs and the function was only used in a couple of unit tests to make sure that passing an alternative significance test works as expected. In other words, the user-supplied significance test is buggy but ANCOM is not.

I think this PR is good to go but will hold off on merging in case you guys want more time in tracking down the differences, or if there are any other objections to merging. Thanks again!

**Comment by mortonjt** [comment]
I have no objections.  @JorgeC, what do you think?

**Comment by Jorge-C** [comment]
Thanks a lot for the summary Jai! :+1: from me too (I've restarded the build to see if the timeout disappears).

**Comment by jairideout** [comment]
Sounds good, will merge! Note that master is timing out for Python 3 builds (#1256).

**Pull request merged**
