### PR TITLE
WIP: add go enrichment analysis

### PR DESCRIPTION
**Pull request by jdrudolph**
This pull request is work in progress and will hopefully lead to the integration of `jdrudolph/goenrich` into `scikit-bio`

@ebolyen I'm making this pull request in response to jdrudolph/goenrich#3. The first commit is only symbolic, but we can discuss here how to proceed.

- [ ] Design

    Currently `goenrich` does not define a single class. It consists of functions on standard data structures only. The aim is to keep the API simple and composable.
How/where should `goenrich` be integrated?
- [ ] Parsing
    - [ ] Custom parser for gene ontology `goenrich.obo`
    - [ ] `pandas` parser for annotations 
- [ ] Documentation
- [ ] Tests

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Thanks in advance for working on this @jdrudolph, great to have you involved in the project!

**Comment by ebolyen** [comment]
@jdrudolph Awesome to have you on board! I think your goals sound great, what we particularly liked was how you were using the scipy-stack to accomplish this. 

- I think the particular functions can go in a new subpackage (name TBD, but goenrich doesn't sound bad to me).

- The parsers would go in `io` ([here](http://scikit-bio.org/docs/latest/generated/skbio.io.registry.html#module-skbio.io.registry) is some documentation on adding new formats to scikit-bio). The parsers (we call them readers) would need to add `monkey_patch=False` to the [reader](http://scikit-bio.org/docs/latest/generated/generated/skbio.io.registry.Format.reader.html#skbio.io.registry.Format.reader) decorator. This way we don't accidentally add methods to NetworkX and Pandas. 

- We use [numpydoc](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) for our documentation. You can browse around any of our code to see examples.

- Tests are super important to us! We have a convenience test-runner `make test` which will run the big parts of our CI suite locally.

**Comment by jairideout** [comment]
@jdrudolph this all sounds good, thanks for your interest in contributing to scikit-bio! I think `skbio.goenrich` is a good subpackage name for the non-I/O components.

To add to @ebolyen's comment, the following resources will be helpful when getting started with scikit-bio development:

- [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md)
- [adding a new module/subpackage to scikit-bio](http://scikit-bio.org/docs/latest/development/new_module.html)
- [documentation guidelines](https://github.com/biocore/scikit-bio/blob/master/doc/README.md)

Please let us know if you have questions or run into any issues, we're happy to help!

**Comment by scikitten-bio** [comment]
## Automated report from asv run
Benchmark run completed successfully. Results available at
[http://powertrip.mggen.nau.edu:5000/runs/jdrudolph/goenrich/html/index.html](http://powertrip.mggen.nau.edu:5000/runs/jdrudolph/goenrich/html/index.html)

**Comment by jdrudolph** [comment]
Using `goenrich` for new projects recently I found it more convenient to use it independently of `skbio`. The pull-request is functional including basic tests etc. but I will not continue to develop `skbio.goenrich` in favor of the original package.

**Pull request closed without merging**
