### PR TITLE
WIP: Interval metadata without genbank

### PR DESCRIPTION
**Pull request by mortonjt**
This is branching off of #1298 without even considering the genbank io modifications.

### CODE REVIEW

**Comment by mortonjt** [comment]
Not sure what is going on here.  These tests are passing on my local machine ...

**Comment by jairideout** [comment]
The Sequence repr changed slightly in https://github.com/biocore/scikit-bio/pull/1323, can you try pulling/rebasing from master?

**Comment by mortonjt** [comment]
🎆 tests pass!  @RNAer @ekopylova @ebolyen @jairideout @gregcaporaso can you guys review this?

**Comment by jairideout** [comment]
@mortonjt see my comment [here](https://github.com/biocore/scikit-bio/pull/1298#issuecomment-207142069) about the next steps for interval metadata in scikit-bio. Reviews are welcome of course but we'd need an RFC to discuss API design, different implementations, dependencies, etc.

**Comment by mortonjt** [comment]
I saw it, and forgot about it :L

Thinking about closing #9 and opening up the a new PR detailing the new design and requirements.  I hope that is ok.

**Comment by jairideout** [comment]
Sounds good, thanks @mortonjt!

**Comment by jairideout** [comment]
Closing in favor of #1356.

**Pull request closed without merging**
