### PR TITLE
Specify test_suite.  Fixes biocore/scikit-bio#1341

### PR DESCRIPTION
**Pull request by genomematt**
Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by jairideout** [comment]
Thanks @genomematt! I tested this locally, comparing `python setup.py test` to `make test`. `make test` runs 2476 tests, while `python setup.py test` only runs 2257 tests, and I get a single test failure:

```
======================================================================
ERROR: test_plot_categorical_legend (skbio.stats.ordination.tests.test_ordination_results.TestOrdinationResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jairideout/miniconda3/envs/scikit-bio/lib/python3.5/site-packages/matplotlib/projections/__init__.py", line 65, in get_projection_class
    return projection_registry.get_projection_class(projection)
  File "/Users/jairideout/miniconda3/envs/scikit-bio/lib/python3.5/site-packages/matplotlib/projections/__init__.py", line 29, in get_projection_class
    return self._all_projection_types[name]
KeyError: '3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jairideout/dev/scikit-bio/skbio/stats/ordination/tests/test_ordination_results.py", line 250, in test_plot_categorical_legend
    ax = fig.add_subplot(111, projection='3d')
  File "/Users/jairideout/miniconda3/envs/scikit-bio/lib/python3.5/site-packages/matplotlib/figure.py", line 987, in add_subplot
    self, *args, **kwargs)
  File "/Users/jairideout/miniconda3/envs/scikit-bio/lib/python3.5/site-packages/matplotlib/projections/__init__.py", line 98, in process_projection_requirements
    projection_class = get_projection_class(projection)
  File "/Users/jairideout/miniconda3/envs/scikit-bio/lib/python3.5/site-packages/matplotlib/projections/__init__.py", line 67, in get_projection_class
    raise ValueError("Unknown projection '%s'" % projection)
ValueError: Unknown projection '3d'
```

Can you look into these issues?

Additionally, please add a note to the changelog under the "miscellaneous" heading saying that tests can now be run with `python setup.py test` in addition to `make test`.

**Comment by genomematt** [comment]
I deliberately did not add a note to the change log as I was not sure it was user ready until the full collection of tests ran.  It's certainly more correct than before.
I suspect that the difference in number of tests is partially plug ins.
`python3 setup.py nosetests` which will use plug ins runs 2300 tests while `python3 setup.py test` runs 2257.
The files these tests are found in are:
```skbio.stats.composition
skbio.stats.composition.centralize
skbio.alignment
skbio.alignment.local_pairwise_align_ssw.
skbio.diversity
skbio.stats.composition.power
skbio.stats.ordination
skbio.stats.power.paired_subsamples
skbio.stats.composition.ilr_inv
skbio.stats.composition.perturb_inv
skbio.io.format.blast6
skbio.io.format.ordination
skbio.io.registry.Format.writer
skbio.sequence.distance.kmer_distance
skbio.tree
skbio.sequence.distance.hamming
skbio.io.format.blast7
skbio.sequence
skbio.stats.gradient
skbio.io.format.stockholm
skbio.stats.composition.closure
skbio.io.format.phylip
skbio.stats.composition.inner
skbio.io.util.open_file
skbio.stats.composition.perturb
skbio.stats.composition.multiplicative_replacement
skbio.io.format.fasta
skbio.stats.composition.ancom
skbio.io.format.clustal
skbio.io.format.newick
skbio.io.format.genbank
skbio.stats.distance
skbio.io.registry.Format.reader
skbio.stats.power.subsample_power
skbio.io.format.fastq
skbio.io
skbio.io.registry.Format.sniffer
skbio.stats.power
skbio.stats.composition.clr_inv
skbio.stats.power.subsample_paired_power
skbio.io.format.qseq
skbio.workflow
skbio.stats.composition.ilr
skbio.stats.composition.clr
```
Note that all do not conform to the .test_foo format and are doctests (note skbio.stats.power.subsample_paired_power fails)

```
------------------------------------------------------------------------------------------------
TOTAL                                                           8048     64   3405     80    99%
----------------------------------------------------------------------
Ran 2300 tests in 63.941s
```
Coverage is actually higher when 2257 tests are run.

```
------------------------------------------------------------------------------------------------
TOTAL                                                           8896     84   3479     81    99%
```

Given the coverage is good I don't see this as a major issue, but it would be nice to know the basis of the difference.  I will continue to potter as I get a chance.

**Comment by jairideout** [comment]
Thanks for digging into this @genomematt! You might check out `skbio.util._testing.TestRunner`, that's what `make test` is using under the hood to invoke nose. Unfortunately I don't have bandwidth to help look into this further.

Sounds good re: changelog -- you can add that to your PR whenever you're ready. I just wanted to note that we'd want the changelog updated before this PR is merged (assuming we can resolve the discrepancies between the test runners). Thanks again for working on this!

**Comment by genomematt** [comment]
I have now made a setup.cfg that matches the `python -m skbio.test` parameters for `python setup.py nosetests`, and added a note in the changelog pointing out that while `python setup.py test` is now functional, it is not as comprehensive as the `nose` based tests.

**Pull request merged**
