### PR TITLE
Added install instruction for NumPy

### PR DESCRIPTION
**Pull request by souravsingh**
Added instructions for NumPy in README.The PR is related to #1296

### CODE REVIEW

**Comment by ebolyen** [comment]
@souravsingh This looks good, but I think the `pip install numpy` should precede `pip install scikit-bio` as the first command will fail without the former. 

In practice, this might be a good time to bump the `conda` install instructions to the top instead of `pip`, `conda` is definitely the easiest way to get running quickly. @jairideout thoughts?

**Comment by jairideout** [comment]
:+1: for moving the conda install instructions above `pip` commands.

@souravsingh part of #1296 is to remove the numpy bootstrap hacks in setup.py. Are you interested in working on that in this pull request? Thanks for your work on this!

**Comment by souravsingh** [comment]
@jairideout I am interested in working on that. How do I start?

**Comment by jairideout** [comment]
@souravsingh here's [the commit](https://github.com/biocore/scikit-bio/commit/371b825520e90764a9699d48543736a0d86465af) that added the numpy bootstrap hack, basically we'd want to revert that (a git commit revert might work, though I haven't tried it).

**Comment by souravsingh** [comment]
I think the numpy bootstrap hack is there in setup.py [here](https://github.com/biocore/scikit-bio/blob/master/setup.py#L20)

**Comment by jairideout** [comment]
@souravsingh, please see the commit I linked to above, that includes all changes that were made to implement the bootstrap hack.

**Comment by ebolyen** [comment]
@souravsingh I'm closing this PR for now, please feel free to re-open if you are still interested

**Pull request closed without merging**
