### PR TITLE
TST: run doctests in Python 3

### LINKED ISSUE #1008: migrate doctests to Python 3

### PR DESCRIPTION
**Pull request by jairideout**
~~**NOT READY FOR MERGE** This should cause some breakage.~~

Status:
- [x] `skbio.workflow`
- [x] `skbio.alignment`
- [x] `skbio.diversity`
- [x] `skbio.draw`
- [x] `skbio.io`
- [x] `skbio.sequence`
- [x] `skbio.stats`
- [x] `skbio.tree`
- [x] `skbio.util`
- [x] final check for unnecessary `u'`/`u"` in docstrings

Fixes #1008.

### CODE REVIEW

**Comment by ebolyen** [comment]
@jairideout your tests are failing. Get it together man.

**Comment by jairideout** [comment]
@ebolyen :speak_no_evil:

**Comment by jairideout** [comment]
@JWDebelius I'm getting `skbio.stats.power` doctest failures with Python 3. For example:

```
File "/Users/jairideout/dev/scikit-bio/skbio/stats/power.py", line 522, in skbio.stats.power.subsample_paired_power
Failed example:
    pwr.mean(0)
Expected:
    array([ 0.196,  0.356,  0.642,  0.87 ])
Got:
    array([ 0.166,  0.416,  0.64 ,  0.902])
```

I think this is happening because `_identify_sample_groups` relies on the ordering of a dictionary (see [here](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/power.py#L1114)). Python 3 has hash randomization enabled (see [here](http://stackoverflow.com/a/14959001/3776794)) so this ordering isn't maintained anymore.

I think iterating over the sorted keys [here](https://github.com/biocore/scikit-bio/blob/master/skbio/stats/power.py#L1114) should fix the issue. Do you see any issues with this?

Note: we don't see *unit test* failures in Python 3 because the tests are only checking basic sanity of the output.

**Comment by JWDebelius** [comment]
I don't see any issue with iterating over sorted keys. I wasn't aware of the issue.

There may also be an issue with randomization. I've had some issues in the past with the randomization and monte carlo simulations in this method.

**Comment by jairideout** [comment]
@JWDebelius thanks for confirming!

**Comment by jairideout** [comment]
@ebolyen this is ready for review.

**Pull request merged**
