### PR TITLE
updates to support most recent dependency versions

### PR DESCRIPTION
**Pull request by gregcaporaso**
Some backward incompatible changes were introduced in pandas 1.5.0 and scipy 1.9.0 that required some updates here (thanks to @SilasK for sharing a fix for this in #1821).

### CODE REVIEW

**Comment by gregcaporaso** [comment]
The current h5py failures seem related to [this issue](https://github.com/conda-forge/h5py-feedstock/issues/92), but the version pinning done there conflicts with our ci version requirement so need to experiment with other versions.

**Comment by ebolyen** [comment]
Ok, USE_CYTHON=TRUE on 3.11 should succeed while USE_CYTHON=FALSE should fail (as a re-render is needed).

**Comment by ebolyen** [comment]
TODO: 
 - update docs to a modern sphinx (`'U'` mode was removed in py3.11 so docutils is raising an error).
 - fix docker build

**Comment by ebolyen** [comment]
Presuming I didn't mess anything up with my rebase, #1832 has cleaned up history.

**Pull request closed without merging**
