### PR TITLE
Normalize grouping

### PR DESCRIPTION
**Pull request by sjanssen2**
Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).
   * please help me deciding if this is a public-facing change. I feel it is the other way around. This PR handles user expectation more faithfully

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by sjanssen2** [comment]
this is addressing #1877

**Comment by sjanssen2** [comment]
Hi @wasade I could need your review on this PR

**Review by wasade — COMMENTED** [review]
This seems very reasonable, and thank you for the regression tests. Can a note of the bug be included in the changelog?

**Comment by sjanssen2** [comment]
@wasade I have added a short description to CHANGELOG.md

**Comment by wasade** [comment]
Thank you @sjanssen2!

**Pull request merged**
