### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### biocore/scikit-bio now has a Chat Room on Gitter

@wasade has just created a chat room. You can visit it here: [https://gitter.im/biocore/scikit-bio](https://gitter.im/biocore/scikit-bio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/biocore/scikit-bio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by wasade** [comment]
@ElDeveloper, I think @gitter-badger should battle @emperor-helper

**Comment by ebolyen** [comment]
This is astounding! Unfortunately it has it in the wrong place, I'll leave this open for reference.

**Comment by wasade** [comment]
@ebolyen, did you notify them? If not, I'll ping

**Comment by ebolyen** [comment]
@wasade no, I am not used to robots giving helpful links...

**Comment by gitter-badger** [comment]
Badger vs. Penguin eh? 
 vs. 

Seriously though, we'll look at getting a fix in for the parsing of your markdown file: https://github.com/gitterHQ/readme-badger/issues/2

**Comment by wasade** [comment]
hahaha, well played @gitter-badger

**Comment by ElDeveloper** [comment]
@emperor-helper would glass @gitter-badger in a second!

**Pull request closed without merging**
