### PR TITLE
ENH: Adding sensible row and column names to biplot_scores in CCA and…

### PR DESCRIPTION
**Pull request by mortonjt**
… RDA

Addresses #1322

### CODE REVIEW

**Comment by jairideout** [comment]
Thanks for the fixes! I noticed that the unit tests are calling `assert_ordination_results_equal` with `ignore_biplot_scores_labels=True`, so I don't think the labels are actually being compared to the expected labels. I can't remember why we added that option to `assert_ordination_results_equal` at the sprint last year. Can it just be removed so that biplot score labels are always compared? You might need to search the codebase for `ignore_biplot_scores_labels` to see where else it's being used, and if we can drop it.

Does this also fix item 2 in #1322?

Can you add a changelog mention? Up to you whether this is tagged as a bug fix or feature enhancement.

Thanks again!

**Comment by mortonjt** [comment]
Right on.

Yeah.  Turns out that only the canonical axes are reported for this.  So
this also fixes part 2.

**Comment by jairideout** [comment]
Awesome! Let me know when you're ready for me to take another pass through.

**Comment by mortonjt** [comment]
Should be good to go!

**Comment by jairideout** [comment]
Thanks @mortonjt!

**Pull request merged**
