### PR TITLE
fix a bug in _intersection.pyx

### PR DESCRIPTION
**Pull request by RNAer**
This addresses #1448. The bug is that I need to change the greater/less-than signs to greater/less-than-or-equal-to sign to search for left/right subtree.

The fact that tests passes in some environment was confusing and misleading. The reason for that behavior is that OSX and linux starts with different interval nodes to search intersection. If it started with the lucky node (as in OSX), it would find the expected nodes; if it is not (as in some cases in linux), it ignored left or right subtree and returned empty.

### CODE REVIEW

**Comment by RNAer** [comment]
@ebolyen and @jairideout , this should fix the bug. Thanks for all the help with debugging! Also big thanks to @wasade for suggesting useful approaches to identify the bug!

**Comment by wasade** [comment]
Wow... good find! Is there an additional test or two which would be beneficial to add?

**Comment by mortonjt** [comment]
Damn.  That is sneaky.  👍 for adding a test.

**Comment by RNAer** [comment]
The root node (the staring node for search) is a bit stochastic because it
tries to do smart things to re-balance the tree so that the interval search
is optimized. Added extra tests - ccording to the code, both left and right
subtrees are tested now.

**Comment by wasade** [comment]
:+1:

**Comment by mortonjt** [comment]
Awesome!

**Comment by ebolyen** [comment]
Amazing. Awesome work @RNAer!

**Pull request merged**
