### PR TITLE
Regenerate Cython wrappers on build by default 

### PR DESCRIPTION
**Pull request by theAeon**
Please complete the following checklist:

* [X] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [X] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by theAeon** [comment]
Closes #1791

**Comment by ebolyen** [comment]
Hi @theAeon! I really appreciate this patch (and thank you for the careful attention to copyright), the bad news is this C file is generated with Cython, so your fix will be overwritten by re-compiles of the Cython.

I wonder if updating Cython and rebuilding the C wrappers would be sufficient to fix the issue?

**Comment by wasade** [comment]
@ebolyen, should the `.c` files be removed actually seeing as they're generated?

**Comment by ebolyen** [comment]
They are left in so that source builds will work without Cython as a dependency.

**Comment by wasade** [comment]
Right, but why not make Cython a dependency? It’s mature, and other biocore projects depend on it as far as I know without issue

**Comment by theAeon** [comment]
I'm with @wasade on this: if Cython was *supposed* to be generating the c files, then we need to make sure its a dependency. Judging by the issue I linked, everyone was using the pregenerated files. This is, of course, assuming that updating cython fixes this issue.

**Comment by theAeon** [comment]
Interesting-regenerating also seems to fix #1796. Probably worth pulling in the MSVC tag regardless in case of a non-cython build.

**Comment by ebolyen** [comment]
Relevant references:
https://www.python.org/dev/peps/pep-0518/
https://www.python.org/dev/peps/pep-0621/

I don't have any first-hand experience working with the new pyproject.toml format, I just know it exists to solve these issues.

**Comment by ebolyen** [comment]
As to why there was an env-var, we treated Cython as a "development dependency". In conda-land, this would probably be called a build dependency. 

It's not needed as something a user would use, but developers should remember to re-render the Cython occasionally to the distributed C code which can then be compiled on the user's side.

It's a bit like how nodejs has just an unending number of transpilers which aren't a runtime dependency of the package, but are definitely needed to modify the source in any meaningful way.

**Comment by theAeon** [comment]
I've been using the pyproject.toml format in my own projects by way of https://github.com/pdm-project/pdm, its honestly ridiculous how easy it is compared to setuptools. Not sure if a full conversion would be necessary to get this running again, though.

**Comment by theAeon** [comment]
Seems we're blocking other projects from supporting 3.10-is there anything that needs to be changed here?

**Comment by tillea** [comment]
Am Sat, Mar 26, 2022 at 01:15:00AM -0700 schrieb Andrew Robbins:
> Seems we're blocking other projects from supporting 3.10-is there anything that needs to be changed here?
Well, you can possibly inspect all patches we apply in the current Debian package which you can find here

    https://salsa.debian.org/med-team/python-skbio/-/tree/master/debian/patches

Kind regards, Andreas.

**Comment by theAeon** [comment]
Oh-I meant from a PR perspective. Forcing cython compilation on works.

**Comment by wasade** [comment]
@theAeon I'm going to merge this now, even though we're breaking on a few builds as the failures appear unrelated. I'll address them in a separate PR. Thanks!

**Pull request merged**
