### PR TITLE
MAINT: Update website for 0.5.4

### PR DESCRIPTION
**Pull request by HannesHolste**
@ElDeveloper : I opened the docs in my browser locally, they rendered correctly. I also checked the docs on the pcoa page describing new fsvd functionality (no browser console errors when rendering that page).

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [x] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
@HannesHolste looks like something went wrong in the process.

Specifically when you click in the "latest" link the page doesn't exist. Can you check this? Also, when clicking around, there appears to be some odd formatting, for example browsing through `scikit-bio/docs/0.5.4/stats.html` there's some odd `======` markup:

screen shot 2018-08-24 at 12 54 03 pm

Which is not present in the current publicly available [version of the docs](
http://scikit-bio.org/docs/0.5.3/stats.html).

**Comment by HannesHolste** [comment]
@ElDeveloper Ah, odd, didn't see that locally on my machine. I'll look into that asap, by 3pm!

**Comment by ElDeveloper** [comment]
Just went over the documentation and when clicking on the 0.5.4 link 
under Docs, it points to 0.5.3. Should be a one line fix in the index.

**Comment by HannesHolste** [comment]
@ElDeveloper ah, thanks for catching that. Fixed.

**Pull request merged**
