### PR TITLE
DOC/BUG: fix links in PR template

### PR DESCRIPTION
**Pull request by jairideout**
Relative links don't appear to work so switched to full URLs.

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by RNAer** [comment]
👍

**Comment by RNAer** [comment]
wait... weirdly, when I click the links, somehow it leads to this mistakenly:
screen shot 2016-11-28 at 4 39 17 pm

**Comment by jairideout** [comment]
Those are the links from the old template that are in my PR description. This PR is fixing them, so that future PR templates will use the correct links.

**Comment by jairideout** [comment]
Thanks!

**Pull request merged**
