### PR TITLE
DOC: Resolving ANCOM documentation confusion

### PR DESCRIPTION
**Pull request by mortonjt**
Resolving confusion in ancom documentation

### CODE REVIEW

**Comment by mortonjt** [comment]
Addresses #1344

**Comment by jairideout** [comment]
The previous wording is confusing but correct. It's listing parametric tests first (one for 2 groups, one for > 2 groups) and nonparametric tests (one for 2 groups, one for > 2 groups). I think that info is useful but needs rewording (it took me several reads to understand it). What about:

"""
The developers of this method recommend the following significance tests: if there are 2 groups, use the standard parametric t-test or non-parametric Wilcoxon rank sum test. If there are more than 2 groups, use parametric one-way ANOVA or nonparametric Kruskal-Wallis. Because one-way ANOVA is equivalent to...
"""

I left out the parenthetical bits but those would still be included in the text.

**Comment by jairideout** [comment]
This looks good but can you add back in the scipy function names? That's what I meant by this sentence in my previous comment:

> I left out the parenthetical bits but those would still be included in the text.

**Comment by mortonjt** [comment]
Sorry.  Added.

**Comment by jairideout** [comment]
Thanks!

**Pull request merged**
