### PR TITLE
 clarify the boundary config of interval features

### PR DESCRIPTION
**Pull request by RNAer**
This is related to #1423 , specifically https://github.com/biocore/scikit-bio/pull/1423#discussion_r80286443

* coordinates system:

`.locations` -> `.bounds`
`.boundaries` -> `.fuzzy`
reverse True/False for fuzzy
add a example to explain in docstring clearly

* update eq/ne:

test lower/upper_bound for equality
use "==" for ne implementation

* update and add tests
* delete a repreated test test_query_negative
* update repr

### CODE REVIEW

**Comment by RNAer** [comment]
need reviews, @mortonjt and @hotdogee

**Comment by RNAer** [comment]
Thanks for catching those! Corrected and updated docstring. Also changed the gene name in that doc example and explicitly said this is hypothetical. @jairideout , mind giving it a quick look and merge?

**Comment by jairideout** [comment]
Thanks @RNAer! Sorry for the delay, I thought I had merged this already :P

**Comment by RNAer** [comment]
Thanks, @jairideout ! I updated the other PR accordingly and all comments are addressed. It is ready for you to review

**Comment by jairideout** [comment]
Great, thank you! I will review it today

**Pull request merged**
