### PR TITLE
Parser function for Partitioned Newick files

### PR DESCRIPTION
**Pull request by kdm9**
Initial work in progress addressing #1305

### CODE REVIEW

**Comment by ebolyen** [comment]
This should ideally be a module in `skbio.io.format`. Either an augmentation of the existing newick parser, or a new format. I don't have strong feelings on that. Then this format could be multiplexed into `read` and `write` and can be used in a variety of contexts. It also looks like having a generator for newick trees is needed. The current newick parser doesn't have a binding for that, but it would be nice to have.

**Comment by jairideout** [comment]
I think making this its own format makes sense since it isn't part of "standard" newick. What we'd want minimally is a generator reader that yields partition lengths and `TreeNode` objects, and have this generator hooked up to the I/O registry. Having a sniffer would be nice to have but not essential.

Adding a generator reader for `newick` format shouldn't be necessary in this PR, agree it would be nice to have at some point.

@kdmurray91 @ebolyen what are your thoughts for a format name? `format='partitioned-newick'`?

**Comment by kdmurray91** [comment]
@jairideout that sounds reasonable. Do you know of another "sub-format" like this that delegates some of the parsing to another parser? I'm not that familiar with the IO submodule.

The above was purely illustrative of the output of the code, I just ported the dodgy function I was using. I'll have a go at a formal format.

I also agree that a generator parser for newick trees would be very useful, there are many cases where you would need one. I will have a go at making one if it turns out to be required for this PR.

**Comment by jairideout** [comment]
@kdmurray91 that all sounds good, thanks!

We don't have another "sub-format" yet (besides Stockholm, which currently doesn't parse the NHX). You should be able to import whatever package-private functions you need from `skbio.io.format.newick` and use those to parse the newick portions of the format. @ebolyen does that sound right to you?

**Comment by ebolyen** [comment]
:+1:

**Comment by kdmurray91** [comment]
Cool, I'll have a go.

**Comment by wasade** [comment]
Closing as this appears to have gone stale, please reopen if this should be finished and merged

**Pull request closed without merging**
