### PR TITLE
Fixing aarch64 float issue

### PR DESCRIPTION
**Pull request by qiyunzhu**
Build on qemu::aarch64-centos raised the following error:

```
#17 808.1 =================================== FAILURES ===================================
#17 808.1 _____________________________ [doctest] skbio.tree _____________________________
#17 808.1 160 C 0.3
#17 808.1 161 D 0.4
#17 808.1 162 E 0.5
#17 808.1 163 root None
#17 808.1 164 
#17 808.1 165 Now let's compare two trees using the distances computed pairwise between tips
#17 808.1 166 in the trees. The distance computed, by default, is the correlation of all
#17 808.1 167 pairwise tip-to-tip distances between trees:
#17 808.1 168 
#17 808.1 169 >>> print(tree1.compare_tip_distances(tree1))  # identity case
#17 808.1 Expected:
#17 808.1     0.0
#17 808.1 Got:
#17 808.1     5.55111512313e-17
```

This is likely a floating-point number precision issue with the architecture. This PR attempts to fix it. Not sure if it will work because I don't have a local aarch64 environment. The trick is that SciPy has a specific distance metric `correlation` which equals to 1 - Pearson's _r_. It can be directly used.

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by qiyunzhu** [comment]
It worked. Yah! All green now. @wasade

**Comment by wasade** [comment]
Awesome :) This PR includes the commits for the CacheControl stuff though which I think are still outstanding on resolution?

**Comment by qiyunzhu** [comment]
@wasade Just wanted to see an "all-green" status :) This PR can be on hold until the CacheControl stuff is resolved.

**Comment by mortonjt** [comment]
Looks good to me.  @wasade merge?

**Pull request merged**
