### PR TITLE
Fixes #840 DOC: improve documentation for teaching purposes

### LINKED ISSUE #840: Filtering high entropy positions (very minor doc improvement)
It would probably be better to have varying positional entropies for teaching purposes in the documentation on this page: 
http://scikit-bio.org/docs/latest/generated/skbio.alignment.Alignment.position_entropies.html?highlight=entropy

from skbio.alignment import Alignment
from skbio.sequence import DNA
sequences = [DNA('AC--', id="seq1"),
                      DNA('AT-C', id="seq2"),
                      DNA('TT-C', id="seq3")]
a1 = Alignment(sequences)
print(a1.position_entropies())
[**0.63651416829481278**, **0.63651416829481278**, nan, nan]

### PR DESCRIPTION
**Pull request by JTFouquier**
Fixes #840, but I had a few issues:  :hand: 

I got this error when running the nosetests so the tests did **not** pass...  you can deny me.  It's okay, I understand...  just trying to learn here!  Thanks! 

    "ImportError: No module named _ssw_wrapper"

Also, I noticed that there was a pep8 error in _trie.py so I fixed that too but didn't make an issue for it since it was just pep8.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Thanks @JTFouquier! Note that the import error you're getting is probably because you don't have the SSW wrapper built locally. If you install with ``pip`` (e.g., ``pip install -e .`` in your virtualenv) I think that should fix it. That's not necessary for this pull request as the travis tests pass and you didn't touch the SSW code.

**Comment by JTFouquier** [comment]
@gregcaporaso, yes that works!!  I got the tests to pass locally.  Different venvs.  Thanks!!

**Comment by gregcaporaso** [comment]
Great!

On Thu, Feb 19, 2015 at 8:08 AM, Jennifer Fouquier <notifications@github.com

**Comment by jairideout** [comment]
Thanks @JTFouquier! FYI the pep8/flake8 error you were getting locally was fixed upstream in #852.

**Pull request merged**
