### PR TITLE
Adding proportion of variance explained to ca (updates #1515)

### PR DESCRIPTION
**Pull request by tanaes**
This PR addresses issue #1345 and essentially just updates PR #1515 from @nreeve17 to the latest master. 

We might also change the variable name if desired. 

--------------------------

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by RNAer** [comment]
test failed.

still voting for `variation_explained`. Looking at the name alone, users may don't get what `proportion` is

**Comment by ElDeveloper** [comment]
I think changing the name to something non-backwards compatible will
likely break depending packages, namely qiime2 and emperor.

**Comment by wasade** [comment]
Would it be possible to add a small test asserting proportion explained is present to avoid an unlikely future regression?

**Comment by tanaes** [comment]
@wasade I think that the existing tests are already checking for the presence of the proportion_explained attribute in the results:

https://github.com/biocore/scikit-bio/blob/b64c33fc9161398340d9dce8496f0d71a242d9d5/skbio/util/_testing.py#L208-L210

**Comment by tanaes** [comment]
yep, although the message is not obvious:

```
======================================================================
FAIL: test_scaling1 (skbio.stats.ordination.tests.test_correspondence_analysis.TestCAResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonsanders/Development/git_sw/scikit-bio/skbio/stats/ordination/tests/test_correspondence_analysis.py", line 169, in test_scaling1
    ignore_directionality=True)
  File "/Users/jonsanders/Development/git_sw/scikit-bio/skbio/util/_testing.py", line 210, in assert_ordination_results_equal
    decimal=decimal)
  File "/Users/jonsanders/Development/git_sw/scikit-bio/skbio/util/_testing.py", line 216, in _assert_series_equal
    assert left_s is None and right_s is None
AssertionError

======================================================================
FAIL: test_scaling2 (skbio.stats.ordination.tests.test_correspondence_analysis.TestCAResults)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonsanders/Development/git_sw/scikit-bio/skbio/stats/ordination/tests/test_correspondence_analysis.py", line 144, in test_scaling2
    ignore_directionality=True)
  File "/Users/jonsanders/Development/git_sw/scikit-bio/skbio/util/_testing.py", line 210, in assert_ordination_results_equal
    decimal=decimal)
  File "/Users/jonsanders/Development/git_sw/scikit-bio/skbio/util/_testing.py", line 216, in _assert_series_equal
    assert left_s is None and right_s is None
AssertionError

----------------------------------------------------------------------
Ran 46 tests in 1.447s

FAILED (failures=2)
```

**Pull request merged**
