### PR TITLE
MAINT: Move _SequenceReprBuilder to separate file

### LINKED ISSUE #1127: Move _SequenceReprBuilder to a separate file
_sequence.py is getting pretty big. Any reason not to move this?

### PR DESCRIPTION
**Pull request by anderspitman**
Now lives in skbio.sequence._repr.py

Closes #1127

### CODE REVIEW

**Comment by ebolyen** [comment]
Ready for merge when tests pass.

**Comment by scikitten-bio** [comment]
## Automated report
Benchmark run completed successfully. Results available at
[http://powertrip.mggen.nau.edu:5000/runs/anderspitman/issue-1127/html/index.html](http://powertrip.mggen.nau.edu:5000/runs/anderspitman/issue-1127/html/index.html)

**Comment by jairideout** [comment]
Can you please move the relevant tests too?

**Comment by jairideout** [comment]
Nevermind, I guess we don't have explicit tests for the repr builder, just the repr itself.

**Pull request merged**
