### PR TITLE
TST: add missing tests for #1684

### PR DESCRIPTION
**Pull request by ebolyen**
Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [x] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

---

This adds tests that we missed in #1684 because Travis wasn't reporting the failure. Thanks to #1694 we discovered that issue.

### CODE REVIEW

**Comment by ElDeveloper** [comment]
@ebolyen can you rebase this branch? That wil include the changes from @Deeeeen and trigger a new CI build.

**Comment by thermokarst** [comment]
@ebolyen, I tried updating the changelog to include this:

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index ce1e8686d..5ac8c13fc 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -38,6 +38,10 @@
 
 * Avoid pandas 1.0.0 import warning ([#1688](https://github.com/biocore/scikit-bio/issues/1688))
 
+* Added support for Python 3.8 and dropped support for Python 3.5.
+
+* This version now depends on `scipy >= 1.3` and `pandas >= 1.0`.
+
 ## Version 0.5.5 (2018-12-10)
 
 ### Features
```

but I can't seem to push (not sure this is a real GH error, or just some permissions issue:

```bash
git push ebolyen pr1684-tests
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 427 bytes | 427.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: Internal Server Error
Everything up-to-date
```

**Comment by thermokarst** [comment]
@ElDeveloper & @wasade - we are hoping to push out a new release of scikit-bio tomorrow that includes fixes related to Pandas 1.0. Do you see any problem with that? While we were fixing up the test suite we noticed that several dependencies no longer have modern packages published on conda or pypi with python 3.5, which is why support was dropped. We added python 3.8 to the build matrix and everything _appears_ okay...

**Comment by ElDeveloper** [comment]
@thermokarst, yes that sounds good to me!

**Pull request merged**
