### PR TITLE
#1122: TabularMSA.sample

### PR DESCRIPTION
**Pull request by dansondergaard**
This PR goes with #1122.

Thought I'd get started on this, so I wrote some tests which all fail at the moment, since no implementation is in place.

If possible I'd like some feedback on the tests. For example, I'm not sure whether I should test the exact result of sampling an alignment (this requires mocking `np.random.choice` or setting `np.random.seed`), or test the important properties of the result (as I do now).

### CODE REVIEW

**Comment by scikitten-bio** [comment]
## Automated report
Benchmark run completed successfully. Results available at
[http://powertrip.mggen.nau.edu:5000/runs/dansondergaard/tabularmsa-sampling/html/index.html](http://powertrip.mggen.nau.edu:5000/runs/dansondergaard/tabularmsa-sampling/html/index.html)

**Comment by scikitten-bio** [comment]
## Automated report
Benchmark run completed successfully. Results available at
[http://powertrip.mggen.nau.edu:5000/runs/dansondergaard/tabularmsa-sampling/html/index.html](http://powertrip.mggen.nau.edu:5000/runs/dansondergaard/tabularmsa-sampling/html/index.html)

**Comment by ebolyen** [comment]
Thanks @dansondergaard these are very nice tests. We also test exact results by setting `np.random.seed`. So testing both properties of the result and the exact result are what we generally do. 

P.S. I'm sorry about the slowness of `__getitem__` we've been preoccupied by other tasks these last two weeks so we are just now jumping back into the swing of things.

**Comment by dansondergaard** [comment]
Cool, @ebolyen. I'll add some more tests. And no prob with `__getitem__` ;)

**Comment by ebolyen** [comment]
@dansondergaard, sorry this dropped off of our radar, `TabularMSA` is a complete object now with a `__getitem__ ` that understands `pandas` indexes. If you are still interested in working on this we would love to have the method!

**Comment by wasade** [comment]
Closing as this appears to have gone stale, please reopen if this should be finished off and merged

**Pull request closed without merging**
