### PR TITLE
BUG: Fix mantel bootstrap on some archs

### PR DESCRIPTION
**Pull request by ebolyen**
Please complete the following checklist:

* [X] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [X] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [X] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

---

I _believe_ this should fix the issues noted in #1785

### CODE REVIEW

**Comment by ebolyen** [comment]
Looks like this is going to work

**Comment by sfiligoi** [comment]
Doesn't this add a significant overhead to the compute?

**Comment by ebolyen** [comment]
@sfiligoi, no it's the difference in `999` permutations and `1000`. That's worthwhile for correctness. If you have a better way to refactor, I am happy to use that instead. But I will insist that our test suite passes. Otherwise we can stick with scipy.pearson.

**Comment by wasade** [comment]
Priority 1 is tests passing. Priority 2 is any addressing fixes if necessary to optimized code

**Comment by sfiligoi** [comment]
> @sfiligoi, no it's the difference in `999` permutations and `1000`. That's worthwhile for correctness. If you have a better way to refactor, I am happy to use that instead. But I will insist that our test suite passes. Otherwise we can stick with scipy.pearson.

Ah, yes... now I understand it better.
Sure, no objections from my side.

**Comment by ebolyen** [comment]
Slightly nicer implementation in https://github.com/biocore/scikit-bio/pull/1787/commits/bb4c04b7b039106d2dc6c5ff26b8d284878deb4f

**Comment by ebolyen** [comment]
Tests have passed, ready for merge if reviewers agree.

**Review by thermokarst — APPROVED** [review]
LGTM, these change all make sense to me - thanks for this @ebolyen!

**Pull request merged**
