### PR TITLE
add appveyor.com yaml config file

### PR DESCRIPTION
**Pull request by genomematt**
Please complete the following checklist:

* [Y] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [Y ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [Y] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by genomematt** [comment]
The travis error is just complaining that the .appveyor.yml is not in sdist.  Actual tests pass

**Comment by jairideout** [comment]
Thanks @genomematt, this is great! Regarding the travis failure, just add `.appveyor.yml` to the `MANIFEST` file to get the tests passing.

@RNAer or @wasade, are either of you available to set up a free appveyor account for scikit-bio? @genomematt needs that to start testing this PR against Windows.

**Comment by RNAer** [comment]
sure! can do it a bit later today

**Comment by RNAer** [comment]
just done setting up appveyor account. @genomematt , I think the file should be `appveyor.yml` without the DOT before it? That's what I see in other repo's and current file don't trigger appveyor to run.

**Comment by genomematt** [comment]
This is running fine on the genomematt/windows branch so I am not quite sure whats going on.
I signed in with GitHub, selected public repos, went to projects, selected add projects > github > sci kit-bio
I may also have had to change the settings under general > branches to build  -> all branches



[cid:79558DC4-AA9E-42E0-A4BD-02C7011D1853@wehi.edu.au]

**Comment by genomematt** [comment]
I also did a pull request between branches on my repo to check the integration at that level and it gave appveyor results.
https://github.com/genomematt/scikit-bio/pull/1

I am happy to help debug but you will need to invite me to the appveyor team.

**Comment by genomematt** [comment]
Ok I had missed a line when copying between the dirty appveyor branch I used for learning how to do it and the clean windows branch I made for the tests.  `build: false` now added back so it does not try and build it as a .net project

**Comment by genomematt** [comment]
Thinking about this @RNAer I actually don't expect anything to happen when you turn on appveyor.  None of the branches have appveyor config files, and I don't think it will do a PR when the branch is not already tested.  Maybe the best approach is to create a windows topic branch on biocore/scikit-bio and have me do the PR against that.
Given we know the test will be failing initially this is probably a prudent approach anyway.
Otherwise you will need to merge this into master before you see any effect.

**Comment by RNAer** [comment]
@genomematt , thanks! I created a `windows-test` branch as you suggested. could you PR against that? BTW, the default appveyor config file is `appveyor.yml`, but it is allowed to customize the file name. I already set it to `.appveyor.yml` as you named it here.

**Comment by genomematt** [comment]
Also note that I am using `python setup.py test` which as is noted in #1341 finds more tests than `make test`

**Comment by RNAer** [comment]
Some tests failed on windows OS. See [here](https://ci.appveyor.com/project/RNAer/scikit-bio).

**Comment by genomematt** [comment]
There are two basic error types here.
The first are real data type specification errors base on not accurately specifying types (e.g. int32 vs int64)
The second are a whole lot of permission errors that are test infrastructure errors not real world errors.
I would in the first instance suggest wrapping skbio\io\tests\test_registry.py", line 66 in a try: … except PermissionError: as a quick and dirty work around.
This will at least expose the underlying tests for now rather than masking them.

A better option might be @pytest.mark.xfail(platform.system() == ''Windows'’, raises=PermissionError)

There are more tests being run than are found with `make test` or `python3 setup.py nosetest` ATM.  I put a pull request against master (#1477) to fix over discovery of tests.

Anyway this is why the windows CI is needed!

**Comment by ebolyen** [comment]
Thanks @genomematt! I think at this point it's probably worth the time to just update `ssw.c` to what the latest is (from: [mengyao/Complete-Striped-Smith-Waterman-Library](https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library)), and then update the types as necessary. It sounds like the fastest way towards Windows compatibility. (We've had a lot of conversations about dropping `ssw.c`, but we've never actually moved towards any replacement.)

**Comment by RNAer** [comment]
@jairideout ，do you have any comments on the test errors on Windows?

@genomematt , do you need a webhook to show the Appveyor check pass/failure (at the end of a PR)? Because it doesn't show now in the PR against `windows-test` branch.

**Comment by ebolyen** [comment]
It also sounds like the PermissionError we're getting is probably going to be because we are failing to close a filehandle in our tests, meaning our process is still using it when `os.remove` is called (I think that should be an easy fix).

**Comment by genomematt** [comment]
Appveyor needs repository web hook admin access and read/write commit statuses @RNAer 
It just worked on my fork.  I suspect the web hook did not get set up correctly.
Try going to https://github.com/settings/applications to check access and reset at https://ci.appveyor.com/account if its not set up.
Also check a web hook is present on https://ci.appveyor.com/project/biocore/scikit-bio/settings and branches to build is `all branches`

**Comment by jairideout** [comment]
> There are more tests being run than are found with `make test` or `python3 setup.py nosetest` ATM.  I put a pull request against master (#1477) to fix over discovery of tests.

See my comment [here](https://github.com/biocore/scikit-bio/pull/1477#issuecomment-273880078), looks like `python setup.py test` is now finding *fewer* tests (along with a test failure) than `make test`. I haven't looked into it, not sure what's going on.

> @jairideout ，do you have any comments on the test errors on Windows?

Unfortunately I don't have the bandwidth to work on this anytime soon, so I don't have specific comments about resolving the errors. Generally, I'd recommend looking into each error and finding an appropriate fix, instead of skipping the failing tests on Windows. We'd want to make sure all issues are fixed before "officially" supporting Windows. In the meantime, hooking up appveyor so that we can see its build status on PRs is really valuable -- reviewers can ignore the failing build unless the contributor introduced a *new* Windows-specific issue in their PR.

Thanks everyone for working on this!

**Comment by RNAer** [comment]
@genomematt , I created that appveyor project page and set as you mentioned. Anyway, I can grant you the permission to update settings in order to test - looks like I will need your email for that?

I created an issue #1479 to track this. It looks like a major task to fix all those Windows test errors. @genomematt , if you are interested in fix any of them, you are absolutely very welcome to do that.

**Comment by wasade** [comment]
Closing as this seems to have gone stale, please reopen if this should be finished off and merged.

**Pull request closed without merging**
