### PR TITLE
DO NOT MERGE. Testing sphinx in travis.

### PR DESCRIPTION
**Pull request by wasade**
Please complete the following checklist:

* [ ] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [ ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [ ] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

### CODE REVIEW

**Comment by wasade** [comment]
We are observing [failures](https://travis-ci.org/biocore/scikit-bio/jobs/232604798#L1173) associated with Pandas version as well (cc #1515, #1511)

**Comment by ElDeveloper** [comment]
I am not 100% sure about this but the failures seem to be gone if you use Python 3.4 but not with Python 3.5/3.6. I was able to reproduce this in two separate installations. Looking at the Travis build this may also be confounded with NumPy 1.11 and 1.12. The two builds that fail are using a version of pandas that's compiled against NumPy 1.12, the build that passes compiles against 1.11. ` ¯\_(ツ)_/¯`.

**Comment by mortonjt** [comment]
Can we close this, since this PR seems pretty empty now?

**Comment by jairideout** [comment]
Closing in favor of #1535

**Pull request closed without merging**
