### PR TITLE
Fix an error on `pip install`

### LINKED ISSUE #1407: pip install on OS X failing
Hi,

I'm running into some trouble installing `scikit-bio`, similar to #981.

When I run `$ pip3 install scikit-bio` I get a lot of output, the main part being building the wheel fails and then building from source fails, both ending with the following error:

```
   building 'skbio.stats.__subsample' extension
    creating build/temp.macosx-10.11-x86_64-3.5
    creating build/temp.macosx-10.11-x86_64-3.5/skbio
    creating build/temp.macosx-10.11-x86_64-3.5/skbio/stats
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c skbio/stats/__subsample.c -o build/temp.macosx-10.11-x86_64-3.5/skbio/stats/__subsample.o
    skbio/stats/__subsample.c:250:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
 ```

I'm running python 3.5, numpy 1.11.1,  and osx 10.11.6.

Thanks for any suggestions

### PR DESCRIPTION
**Pull request by bsmith89**
Closes #1407.

Based on a StackOverflow answer: http://stackoverflow.com/a/14657667/1951857

Sorry that I haven't followed all of the guidelines in `CONTRIBUTING.md`, but this is a pretty quick fix.

It's possible that this the error being fixed is Python3 specific.  This has not been fully tested.

### CODE REVIEW

**Comment by ebolyen** [comment]
Thanks @bsmith89, the code looks good. If I understand this correctly, what is happening is the latest `distutils` doesn't pass the `include_dirs` argument in `setup` to the `Extension`s anymore? I saw that in a comment of your linked SO post, but I can't find an authoritative source on that.

**Comment by bsmith89** [comment]
Yeah, I have no idea when the problem was introduced.

I'm on Python 3, `numpy` 1.11.1, `pip` 8.1.2, and `setuptools` 25.1.5.

Sorry I can't be more helpful.

**Comment by ebolyen** [comment]
No worries @bsmith89, this PR is very helpful, I don't think we would have assumed anything was wrong with `include_dirs` for a long time, so you've already potentially saved us a lot of headaches.

Now we just have to reproduce to prove that we can fix it.

**Comment by ebolyen** [comment]
@bsmith89 We were able to reproduce, could you add a changelog notice under `Bug Fixes` mentioning that numpy linking was fixed for installation under El Capitan? This looks good to merge afterwards!

**Comment by jairideout** [comment]
Thanks for the fix @bsmith89!

**Pull request merged**
